<?php

namespace App\Helper;

abstract class Categories
{
    const CATEGORIES = [
        "1" => [
            "age_min" => "6",
            "age_max" => "8",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "9. Kyu",
            "sex" => "m",
            "examination_type" => "Kihon",
        ],
        "2" => [
            "age_min" => "6",
            "age_max" => "8",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "9. Kyu",
            "sex" => "w",
            "examination_type" => "Kihon",
        ],
        "3" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "9. Kyu",
            "sex" => "m",
            "examination_type" => "Kihon",
        ],
        "4" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "9. Kyu",
            "sex" => "w",
            "examination_type" => "Kihon",
        ],
        "5" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "9. Kyu",
            "sex" => "m",
            "examination_type" => "Kihon",
        ],
        "6" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "9. Kyu",
            "sex" => "w",
            "examination_type" => "Kihon",
        ],
        "7" => [
            "age_min" => "6",
            "age_max" => "8",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "8" => [
            "age_min" => "6",
            "age_max" => "8",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "9" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "10" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "11" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "12" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "13" => [
            "age_min" => "6",
            "age_max" => "8",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "14" => [
            "age_min" => "6",
            "age_max" => "8",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "15" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "16" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "17" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "18" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "8. Kyu",
            "graduation_max" => "8. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "19" => [
            "age_min" => "8",
            "age_max" => "12",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m/w",
            "examination_type" => "Team",
        ],
        "20" => [
            "age_min" => "13",
            "age_max" => "20",
            "graduation_min" => "9. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m/w",
            "examination_type" => "Team",
        ],
        "21" => [
            "age_min" => "8",
            "age_max" => "10",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "22" => [
            "age_min" => "8",
            "age_max" => "10",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "23" => [
            "age_min" => "8",
            "age_max" => "10",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "24" => [
            "age_min" => "8",
            "age_max" => "10",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "25" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "26" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "27" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "28" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "29" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "30" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "31" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "32" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "33" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "34" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "35" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "36" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "37" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "38" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "39" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "40" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "41" => [
            "age_min" => "21",
            "age_max" => "99",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kata",
        ],
        "42" => [
            "age_min" => "21",
            "age_max" => "99",
            "graduation_min" => "5. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kata",
        ],
        "43" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m/w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "44" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "45" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "46" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "47" => [
            "age_min" => "9",
            "age_max" => "10",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "48" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m/w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "49" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "50" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "51" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "52" => [
            "age_min" => "11",
            "age_max" => "12",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "53" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m/w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "54" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "55" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "56" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "57" => [
            "age_min" => "13",
            "age_max" => "14",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "58" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "7. Kyu",
            "graduation_max" => "6. Kyu",
            "sex" => "m/w",
            "examination_type" => "Kumite (Kihon Ippon)",
        ],
        "59" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "60" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "61" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "62" => [
            "age_min" => "15",
            "age_max" => "17",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "63" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "m",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "64" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "4. Kyu",
            "sex" => "w",
            "examination_type" => "Kumite (Jiyu Ippon)",
        ],
        "65" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "66" => [
            "age_min" => "18",
            "age_max" => "20",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "67" => [
            "age_min" => "21",
            "age_max" => "99",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "m",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
        "68" => [
            "age_min" => "21",
            "age_max" => "99",
            "graduation_min" => "6. Kyu",
            "graduation_max" => "6. Dan",
            "sex" => "w",
            "examination_type" => "Kumite (Shobu Ippon)",
        ],
    ];
}
