name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration - Laravel test"]
    types:
      - completed
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./sv-tora
    defaults:
      run:
        working-directory: ./sv-tora
        
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Laravel Mix CSS Bundling
        run: npm run prod
      - name: Webpack JS Bundling
        run: npm run webpack_prod
      - name: Upload to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.strato.de
          port: 21
          username: svtora@sv-tora.weberlin-design.de
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: "./sv-tora/"
          server-dir: "./"
          exclude: .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
