name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration - Laravel test"]
    branches: [main]
    types:
      - completed
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./sv-tora
    defaults:
      run:
        working-directory: ./sv-tora
    if: ${{ github.event.workflow_run.conclusion == "success" }}
        
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Laravel Mix CSS Bundling
        run: npm run prod
      - name: Webpack JS Bundling
        run: npm run webpack_prod
      - name: Upload to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 81.169.254.132
          port: 22
          username: sv_tora@h2955237.stratoserver.net
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: "./sv-tora/"
          server-dir: "./../../var/www/sv-tora/"
          exclude: .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
            - vendor/**
            - vendor/**/*
